"""add note timestamp

Revision ID: 20bbec48e9ce
Revises: 
Create Date: 2021-12-01 22:31:00.319482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20bbec48e9ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('desp', sa.String(length=300), nullable=True),
    sa.Column('tpl_list', sa.String(length=300), nullable=True),
    sa.Column('tpl_page', sa.String(length=300), nullable=True),
    sa.Column('tpl_mold', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('seo_title', sa.String(length=100), nullable=True),
    sa.Column('seo_description', sa.String(length=300), nullable=True),
    sa.Column('seo_keywords', sa.String(length=300), nullable=True),
    sa.Column('sn', sa.Integer(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_index(op.f('ix_category_title'), 'category', ['title'], unique=True)
    op.create_table('friendly_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=False, comment='连接'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='名称'),
    sa.Column('state', sa.Boolean(), nullable=True, comment='状态'),
    sa.Column('ctime', sa.DateTime(), nullable=True, comment='时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitation_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('online_tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('desp', sa.String(length=120), nullable=True),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('sn', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notify_time', sa.DateTime(), nullable=True),
    sa.Column('notify_type', sa.String(length=200), nullable=True),
    sa.Column('trade_status', sa.String(length=200), nullable=True),
    sa.Column('out_trade_no', sa.String(length=200), nullable=True),
    sa.Column('buyer_logon_id', sa.String(length=200), nullable=True),
    sa.Column('total_amount', sa.String(length=30), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('paystate', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pay_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('callbacktime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=120), nullable=True),
    sa.Column('remark', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('sn', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skey', sa.String(length=64), nullable=True),
    sa.Column('svalue', sa.String(length=800), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setting_skey'), 'setting', ['skey'], unique=True)
    op.create_table('spider_include',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_engine', sa.String(length=64), nullable=False, comment='搜索引擎'),
    sa.Column('num', sa.Integer(), nullable=False, comment='收录数量'),
    sa.Column('time_label', sa.String(length=20), nullable=False, comment='时间标签'),
    sa.Column('ctime', sa.DateTime(), nullable=True, comment='时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_code'), 'tag', ['code'], unique=True)
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('email_state', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('website', sa.String(length=128), nullable=False, comment='网址'),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True, comment='1=管理员,0=普通账号,3=vip'),
    sa.Column('avatar', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('editor', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('thumbnail', sa.String(length=200), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('vc', sa.Integer(), nullable=True),
    sa.Column('comment_num', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('h_content', sa.String(length=800), nullable=False),
    sa.Column('h_role', sa.Integer(), nullable=True, comment='1=管理员,2=普通账号,3=vip'),
    sa.Column('is_crawl', sa.Integer(), nullable=True, comment='0=作者字写，1=抓取内容'),
    sa.Column('origin_url', sa.String(length=200), nullable=True, comment='抓取内容的原始url'),
    sa.Column('origin_author', sa.String(length=100), nullable=True, comment='原作者'),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_name'), 'article', ['name'], unique=True)
    op.create_index(op.f('ix_article_timestamp'), 'article', ['timestamp'], unique=False)
    op.create_index(op.f('ix_article_title'), 'article', ['title'], unique=False)
    op.create_table('article_tag',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='关联的文章id'),
    sa.Column('content', sa.String(length=1024), nullable=True),
    sa.Column('reply_id', sa.Integer(), nullable=True, comment='回复对应的评论id'),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['reply_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('article_tag')
    op.drop_index(op.f('ix_article_title'), table_name='article')
    op.drop_index(op.f('ix_article_timestamp'), table_name='article')
    op.drop_index(op.f('ix_article_name'), table_name='article')
    op.drop_table('article')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_index(op.f('ix_tag_code'), table_name='tag')
    op.drop_table('tag')
    op.drop_table('spider_include')
    op.drop_index(op.f('ix_setting_skey'), table_name='setting')
    op.drop_table('setting')
    op.drop_table('recommend')
    op.drop_table('picture')
    op.drop_table('order_log')
    op.drop_table('online_tool')
    op.drop_table('invitation_code')
    op.drop_table('friendly_link')
    op.drop_index(op.f('ix_category_title'), table_name='category')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    op.drop_table('access_log')
    # ### end Alembic commands ###
